logging:
  config: classpath:log4j2.xml
  level:
    org:
      springframework:
        web: INFO
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: finance
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@127.0.0.1:1521:paydb
    username: oracle
    password: oracle
    #druid连接池配置
    druid:
      #初始化大小，最小，最大
      initialSize: 5
      minIdle: 5
      maxActive: 300
      #配置获取连接等待超时的时间
      maxWait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      #配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      #打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      #通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=3000
      #合并多个DruidDataSource的监控数据
      #useGlobalDataSourceStat: true
mybatis:
  type-aliases-package: com.cah.repository
  mapper-locations: classpath*:mapper/*Mapper.xml
management:
  security:
    enabled: false

